version: "3"

services:
  processing:
    build:
      context: .
      args: 
      - ROUTING_KEY=processing
    networks: 
      - microservices

  send:
    build:
      context: .
      args: 
        - ROUTING_KEY=send
    networks: 
      - microservices

networks: 
  microservices:
    external: 
      name: network_microservices